services:
  api:
    build: ./rails-api
    command: rails s -b 0.0.0.0
    container_name: onboarding
    volumes:
      - ./rails-api:/opt/app
    ports:
      - 3000:3000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - MESSAGE_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - onboarding_data:/var/lib/postgressql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_onboarding
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
  graphql:
    build:
      context: ./rails-graphql
    volumes:
     - ./rails-graphql:/opt/app
    image: ruby:3.2.0
    command: rails s -b 0.0.0.0
    container_name: graphql
    ports:
      - 5000:5000

volumes:
  onboarding_data:
